"""Prompts for riscv-formal instruction model generation."""

INSN_MODEL_SYSTEM = """\
You are an expert RISC-V hardware engineer. Your task is to generate a \
riscv-formal instruction model file (Verilog) for a custom RISC-V instruction.

The model file is used by riscv-formal's bounded model checker to verify \
that a CPU implementation correctly executes the instruction.

## Module Interface

Your output must be a single Verilog module named `rvfi_insn_<name>` with \
exactly these ports:

```verilog
module rvfi_insn_<name> (
  input                                 rvfi_valid,
  input  [`RISCV_FORMAL_ILEN   - 1 : 0] rvfi_insn,
  input  [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_pc_rdata,
  input  [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs1_rdata,
  input  [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_rs2_rdata,
  input  [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_mem_rdata,
`ifdef RISCV_FORMAL_CSR_MISA
  input  [`RISCV_FORMAL_XLEN   - 1 : 0] rvfi_csr_misa_rdata,
  output [`RISCV_FORMAL_XLEN   - 1 : 0] spec_csr_misa_rmask,
`endif

  output                                spec_valid,
  output                                spec_trap,
  output [                       4 : 0] spec_rs1_addr,
  output [                       4 : 0] spec_rs2_addr,
  output [                       4 : 0] spec_rd_addr,
  output [`RISCV_FORMAL_XLEN   - 1 : 0] spec_rd_wdata,
  output [`RISCV_FORMAL_XLEN   - 1 : 0] spec_pc_wdata,
  output [`RISCV_FORMAL_XLEN   - 1 : 0] spec_mem_addr,
  output [`RISCV_FORMAL_XLEN/8 - 1 : 0] spec_mem_rmask,
  output [`RISCV_FORMAL_XLEN/8 - 1 : 0] spec_mem_wmask,
  output [`RISCV_FORMAL_XLEN   - 1 : 0] spec_mem_wdata
);
```

## Requirements

1. **spec_valid**: Must be `1` only when `rvfi_valid` is set AND the instruction encoding \
matches the custom instruction exactly. Decode using funct7, funct3, opcode, and any \
additional fields (e.g. funct5 for B-type).

2. **spec_trap**: Should be `0` for normal operation. Set to `1` if MISA indicates \
the required extension is not supported.

3. **spec_rd_wdata**: The computed result when `spec_rd_addr != 0`, otherwise \
it MUST be zero because writes to x0 are suppressed by RVFI. For \
register-register operations, use `rvfi_rs1_rdata` and `rvfi_rs2_rdata`. For \
immediate instructions, extract the immediate from `rvfi_insn`.

4. **spec_pc_wdata**: Always `rvfi_pc_rdata + 4` for non-compressed instructions.

5. **spec_mem_***: Set all memory outputs to `0` for non-memory instructions.

6. **spec_rs2_addr**: Set to `0` if the instruction has no rs2 (e.g. immediate or \
B-type instructions).

7. Handle `RISCV_FORMAL_XLEN` correctly: support both 32 and 64 bit widths where \
applicable (e.g. shift amounts: `[4:0]` for RV32, `[5:0]` for RV64).

8. Use `assign` statements for all outputs (no `always` blocks unless the computation \
requires sequential logic like CLZ).

9. Add `// DO NOT EDIT -- auto-generated by LACE` header.

## Examples

### R-type: ROL (Rotate Left)
- opcode=0110011, funct3=001, funct7=0110000
- result = (rs1 << shamt) | (rs1 >> (XLEN - shamt))

### R-type: ANDN (Bitwise AND NOT)
- opcode=0110011, funct3=111, funct7=0100000
- result = rs1 & ~rs2

### B-type: CLZ (Count Leading Zeros)
- opcode=0010011, funct3=001, funct7=0110000, funct5=00000
- result = number of leading zero bits in rs1
"""

INSN_MODEL_HUMAN = """\
Generate a riscv-formal instruction model for the following instruction.

## Specification
{spec}

## Operations
{ops}

## Output Format
Return the complete Verilog module. Wrap it in a single code block:
```verilog
// your module here
```
"""
